### ISSUE TITLE
docker-compose wrong container name autocomplete

### ISSUE THREAD

**Issue by iskhomutov** [robbyrussell/oh-my-zsh#7092]
Autocomplete is not working properly, if the 'container_name' property in docker-compose.yml has '_' symbol.
Screenshot:
![screenshot_26082018_201323](https://user-images.githubusercontent.com/17610400/44630868-cca92780-a96c-11e8-9ee3-3662d4eb50d4.png)

**Comment by mcornella** [comment]
I can't reproduce your behavior, can you post your `docker-compose.yml`?

**Comment by iskhomutov** [comment]
```yaml
version: '2'
services:
  db1:
    image: postgres:latest
    container_name: postgres_test
  rs1:
    image: redis:latest
    container_name: redis_test
```

**Comment by mcornella** [comment]
Ok, so the thing is that docker-compose's completion expects you to have defined your service's name like so
```yaml
version: '2'
services:
  postgres_test:
    image: postgres:latest
  redis_test:
    image: redis:latest
```
This has the effect that the real container names generated by docker-compose are of the form `${dirname}_${servicename}_${number}` so, to get the service name, the completion strips away the first and last parts separated by underscores.

When instead you define the container_name like you did, the completion cannot get the service name from the container name, because it wasn't automatically generated.

To my knowledge there is no other solution than to not use custom container_names, or avoid completion altogether. You can open an issue on the official repo; here's a related issue https://github.com/docker/compose/pull/4313
