### ISSUE TITLE
docker-compose plugin autocompleting wrong for start|stop|restart|exec

### ISSUE THREAD

**Issue by MartyBeGood** [robbyrussell/oh-my-zsh#7411]
On completing `docker-compose <start|stop|restart>` the autocompletion suggests container names instead of service names.

Example (just off the top of my head):
someproject/docker-compose.yml
```yml
version: '3.5'
services:
  app:
    <some config>
  db:
    <some other config>
```

`docker-compose up -d` reveals the following container names:
- someproject_app_1_<random_hash>
- someproject_db_1_<random_hash>

`docker-compose restart <tab>` should autocomplete `app` or `db`, but currently it suggests `app_1` and `db_1`
